// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
var _SERVER_URL = 'http://192.168.16.112:8760';//'http://&REPLACE_HOST&:&REPLACE_PORT&';
//http://192.168.16.122:8888
// http://&REPLACE_HOST&:&REPLACE_PORT&
export const SERVER_URL = _SERVER_URL;

function getAuthorization() {
    try{
        if(sessionStorage){
            return 'Bearer ' + sessionStorage['authenticationToken'];
        }
    }catch (e){
        var mainObj = document.getElementById('userData');
        try{
            mainObj.load('LoginDataStore');
            console.log(mainObj.getAttribute('authenticationToken'));
            return 'Bearer ' + mainObj.getAttribute('authenticationToken');
        }catch(e){

        }
    }
}

export function getHeaders() {
    let headers = {};
    headers['Content-Type']= 'application/json';//'text/plain';
    headers['Accept']= 'application/json';
    headers['Authorization']= getAuthorization();
    // headers['Mime-Type'] = 'application/json;charset=UTF-8';
    //console.log(JSON.stringify(headers))
    return headers;
}